LOG_CORRECT = "LOG_CORRECT"
LOG_WRONG = "LOG_WRONG"
LOG_HINT = "LOG_HINT"
LOG_DEMO = "LOG_DEMO"
LOG_POST = "LOG_POST"
# LOG_PRACTICE = "LOG_PRACT"

ATYPE_SPPP = "SPPP_TYPE"
ATYPE_SPSP = "SPSP_TYPE"
ATYPE_F = "F_TYPE"
ATYPE_S = "S_TYPE"

INTERACTION_TYPE_PRETRAIN = "pretrain"
INTERACTION_TYPE_PRETEST = "pre"
INTERACTION_TYPE_POSTTEST = "post"
INTERACTION_TYPE_STUDY = "study"

SKILL = 'skill'
FACT = 'fact'

KTYPE_SKILL = 'S_TYPE'
KTYPE_FACT = 'F_TYPE'
COND_SPPP = 'SPPP_TYPE'
COND_SPSP = 'SPSP_TYPE'

PTYPE_DEMO = 'demo'
PTYPE_PRACTICE = 'practice'

TT_PRETRAIN = "pretrain"
TT_PRETEST = "pre"
TT_POSTTEST = "post"
TT_STUDY = "study"
